measures_config:
    AngularVelocity:
        standard: RADIAN_PER_SECOND
        units:
            RADIAN_PER_SECOND:
                convert: [{'mul': 1}]
                symbol: rad/s
            REVOLUTION_PER_MINUTE:
                convert: [{'mul': 0.1047198}]
                symbol: r/min
