measures_config:
    RotationalFrequency:
        standard: REVOLUTION_PER_SECOND
        units:
            REVOLUTION_PER_SECOND:
                unece_code: 'RPS'
                convert: [{'mul': 1}]
                symbol: 'r/s'
            REVOLUTION_PER_MINUTE:
                unece_code: 'RPM'
                convert: [{'mul': 60}]
                symbol: 'r/min'
