measures_config:
    Speed:
        standard: METER_PER_SECOND
        units:
            METER_PER_SECOND:
                unece_code: 'MTS'
                convert: [{'mul': 1}]
                symbol: 'm/s'
                name: 'meter per second'
            METER_PER_MINUTE:

                convert: [{'div': 60}]
                symbol: mdivm
            METER_PER_HOUR:
                convert: [{'mul': 1}, {'div': 3600}]
                symbol: mdivh
            KILOMETER_PER_HOUR:
                unece_code: 'KMH'
                convert: [{'mul': 1000}, {'div': 3600}]
                symbol: 'km/h'
                name: 'kilometer per hour'
            FOOT_PER_SECOND:
                convert: [{'mul': 0.3048}]
                symbol: ftdivs
            FOOT_PER_HOUR:
                convert: [{'mul': 0.3048}, {'div': 3600}]
                symbol: ftdivh
            YARD_PER_HOUR:
                convert: [{'mul': 0.9144'}, {'div': 3600}]
                symbol: yddivh
            MILE_PER_HOUR:
                convert: [{'mul': 1609.344}, {'div': 3600}]
                symbol: midivh

            # Added
            KNOT:
                unece_code: 'KNT'
                convert: [{'mul': 0.514444}]
                symbol: 'kn'
                name: 'knot'
            MILLIMETER_PER_SECOND:
                unece_code: 'C16'
                convert: [{'div': 1000}]
                symbol: 'mm/s'
                name: 'millimeter per second'
            CENTIMETER_PER_SECOND:
                unece_code: '2M'
                convert: [{'div': 100}]
                symbol: 'cm/s'
                name: 'centimeter per second'
            CENTIMETER_PER_HOUR:
                unece_code: 'H49'
                convert: [{'div': 360000}]
                symbol: 'cm/h'
                name: 'centimeter per hour'
            MILLIMETER_PER_MINUTE:
                unece_code: 'C16'
                convert: [{'div': 60000}]
                symbol: 'mm/min'
                name: 'millimeter per minute'
            METER_PER_MINUTE:
                unece_code: '2X'
                convert: [{'div': 60}]
                symbol: 'm/min'
                name: 'meter per minute'
